OUTPUT_ARCH(riscv)
ENTRY(__start)

MEMORY
{
    sram (rwx) : ORIGIN = 0x30040000, LENGTH = 64K
}

SECTIONS
{
    .text : {
        _stext = .;
        *(.text .text.*)
        *(.rodata .rodata.*)
        . = ALIGN(4);
        _etext = .;
    } > sram

    .data : {
        _sdata = .;
        *(.data .data.*)
        *(.sdata .sdata.*)
        . = ALIGN(4);
        _edata = .;
    } > sram

    .bss : {
        _sbss = .;
        *(.bss .bss.*)
        *(.sbss .sbss.*)
        *(COMMON)
        . = ALIGN(16);
        _ebss = .;
    } > sram

    .stack (NOLOAD) : {
        . = ALIGN(16);
        . = . + 4096;
        . = ALIGN(16);
        _estack = .;
    } > sram

    .heap (NOLOAD) : {
        . = ALIGN(16);
        _sheap = .;
        _eheap = ORIGIN(sram) + LENGTH(sram);
    } > sram
}
